<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Sauce_Demo_Data_Driven" duration-ms="29308" started-at="2021-04-26T10:23:27Z" finished-at="2021-04-26T10:23:56Z">
    <groups>
    </groups>
    <test name="Sauce Demo Positive Data Test" duration-ms="10377" started-at="2021-04-26T10:23:27Z" finished-at="2021-04-26T10:23:37Z">
      <class name="Multiple_Test_scripts.Sauce_Demo_Data_Driven">
        <test-method status="PASS" signature="Beforetest()[pri:0, instance:Multiple_Test_scripts.Sauce_Demo_Data_Driven@32d992b2]" name="Beforetest" is-config="true" duration-ms="3346" started-at="2021-04-26T06:23:27Z" finished-at="2021-04-26T06:23:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Beforetest -->
        <test-method status="PASS" signature="GoToHomePage()[pri:0, instance:Multiple_Test_scripts.Sauce_Demo_Data_Driven@32d992b2]" name="GoToHomePage" is-config="true" duration-ms="91" started-at="2021-04-26T06:23:30Z" finished-at="2021-04-26T06:23:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GoToHomePage -->
        <test-method status="FAIL" signature="validatingLogin(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Multiple_Test_scripts.Sauce_Demo_Data_Driven@32d992b2]" name="validatingLogin" duration-ms="4611" started-at="2021-04-26T06:23:31Z" finished-at="2021-04-26T06:23:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[https://www.saucedemo.com/inventory.html]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at Multiple_Test_scripts.Sauce_Demo_Data_Driven.validatingLogin(Sauce_Demo_Data_Driven.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatingLogin -->
        <test-method status="PASS" signature="TakenScreenShots()[pri:0, instance:Multiple_Test_scripts.Sauce_Demo_Data_Driven@32d992b2]" name="TakenScreenShots" is-config="true" duration-ms="376" started-at="2021-04-26T06:23:35Z" finished-at="2021-04-26T06:23:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TakenScreenShots -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:Multiple_Test_scripts.Sauce_Demo_Data_Driven@32d992b2]" name="endTest" is-config="true" duration-ms="1919" started-at="2021-04-26T06:23:36Z" finished-at="2021-04-26T06:23:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- Multiple_Test_scripts.Sauce_Demo_Data_Driven -->
    </test> <!-- Sauce Demo Positive Data Test -->
    <test name="Sauce Demo Negative Data Test" duration-ms="9461" started-at="2021-04-26T10:23:37Z" finished-at="2021-04-26T10:23:47Z">
      <class name="Multiple_Test_scripts.Sauce_Demo_Data_Driven">
        <test-method status="PASS" signature="Beforetest()[pri:0, instance:Multiple_Test_scripts.Sauce_Demo_Data_Driven@1753acfe]" name="Beforetest" is-config="true" duration-ms="2680" started-at="2021-04-26T06:23:37Z" finished-at="2021-04-26T06:23:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Beforetest -->
        <test-method status="PASS" signature="GoToHomePage()[pri:0, instance:Multiple_Test_scripts.Sauce_Demo_Data_Driven@1753acfe]" name="GoToHomePage" is-config="true" duration-ms="113" started-at="2021-04-26T06:23:40Z" finished-at="2021-04-26T06:23:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GoToHomePage -->
        <test-method status="PASS" signature="validatingLogin(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Multiple_Test_scripts.Sauce_Demo_Data_Driven@1753acfe]" name="validatingLogin" duration-ms="4442" started-at="2021-04-26T06:23:40Z" finished-at="2021-04-26T06:23:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[locked_out_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[https://www.saucedemo.com/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatingLogin -->
        <test-method status="PASS" signature="TakenScreenShots()[pri:0, instance:Multiple_Test_scripts.Sauce_Demo_Data_Driven@1753acfe]" name="TakenScreenShots" is-config="true" duration-ms="352" started-at="2021-04-26T06:23:45Z" finished-at="2021-04-26T06:23:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TakenScreenShots -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:Multiple_Test_scripts.Sauce_Demo_Data_Driven@1753acfe]" name="endTest" is-config="true" duration-ms="1872" started-at="2021-04-26T06:23:45Z" finished-at="2021-04-26T06:23:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- Multiple_Test_scripts.Sauce_Demo_Data_Driven -->
    </test> <!-- Sauce Demo Negative Data Test -->
    <test name="Sauce Demo problem user Data Test" duration-ms="9436" started-at="2021-04-26T10:23:47Z" finished-at="2021-04-26T10:23:56Z">
      <class name="Multiple_Test_scripts.Sauce_Demo_Data_Driven">
        <test-method status="PASS" signature="Beforetest()[pri:0, instance:Multiple_Test_scripts.Sauce_Demo_Data_Driven@675d3402]" name="Beforetest" is-config="true" duration-ms="2673" started-at="2021-04-26T06:23:47Z" finished-at="2021-04-26T06:23:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Beforetest -->
        <test-method status="PASS" signature="GoToHomePage()[pri:0, instance:Multiple_Test_scripts.Sauce_Demo_Data_Driven@675d3402]" name="GoToHomePage" is-config="true" duration-ms="130" started-at="2021-04-26T06:23:50Z" finished-at="2021-04-26T06:23:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GoToHomePage -->
        <test-method status="FAIL" signature="validatingLogin(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Multiple_Test_scripts.Sauce_Demo_Data_Driven@675d3402]" name="validatingLogin" duration-ms="4427" started-at="2021-04-26T06:23:50Z" finished-at="2021-04-26T06:23:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[problem_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[https://www.saucedemo.com/inventory.html]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at Multiple_Test_scripts.Sauce_Demo_Data_Driven.validatingLogin(Sauce_Demo_Data_Driven.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatingLogin -->
        <test-method status="PASS" signature="TakenScreenShots()[pri:0, instance:Multiple_Test_scripts.Sauce_Demo_Data_Driven@675d3402]" name="TakenScreenShots" is-config="true" duration-ms="318" started-at="2021-04-26T06:23:54Z" finished-at="2021-04-26T06:23:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TakenScreenShots -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:Multiple_Test_scripts.Sauce_Demo_Data_Driven@675d3402]" name="endTest" is-config="true" duration-ms="1886" started-at="2021-04-26T06:23:54Z" finished-at="2021-04-26T06:23:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- Multiple_Test_scripts.Sauce_Demo_Data_Driven -->
    </test> <!-- Sauce Demo problem user Data Test -->
  </suite> <!-- Sauce_Demo_Data_Driven -->
</testng-results>
